version: "3.9"

services: 
    database:
        image: postgres
        container_name: database_imaginebox
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=imaginebox
            - POSTGRES_PASSWORD=alohomora
            - POSTGRES_DB=imaginebox
        volumes: 
            - pgdata:/data/postgres
    backend:
        build: .
        container_name: imaginebox
        ports: 
            - 3333:3333
            - 9229:9229
        volumes: 
            - .:/usr/app
        links: 
            - database
        depends_on: 
            - database

volumes:
    pgdata:
        driver: local